### ISSUE TITLE
[Feature] uv tiling and offset is work now 

### ISSUE THREAD

**Issue by sonygod** [sketchfab/Unity-glTF-Exporter#28]
https://skfb.ly/69VIM  uv offset and tiling work
https://skfb.ly/69VIN   uv offset and tiling not work. base version

![image](https://user-images.githubusercontent.com/748320/32268473-2fcd5d50-bf2a-11e7-8c5a-28a6120f6720.png)

I will upload  sample code here

https://gist.github.com/sonygod/89401b5f0bb8c1f187d319c3ecc09a71

**Comment by AurL** [comment]
Hi, 

Just dropping a note here even if it's closed. 
I'm glad you found a solution and thanks for sharing it! 

I don't think it could be included in the exporter for now since it requires data duplication/alteration to achieve this. The proper way would be to have tillig/offset property in glTF as you [mentionned here](https://github.com/KhronosGroup/glTF/issues/1141) or as [mentionned here](https://github.com/KhronosGroup/glTF/pull/1015) to allow transporting it through glTF and then to have it supported on Sketchfab. If glTF adds it, it will make sense for us to support such option.

Maybe we will consider this and check with glTF community to see if it makes sense.

Thanks again!

**Comment by sonygod** [comment]
I close this because although  this method  can show uv,but there is an very important note:
texture quality will low down....so,when we want to show very hight quality  model,this way can't be use
